server:
  port: 8080

spring:
  application:
    name: anomaly-service
  profiles:
    default: dev

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never