apiVersion: v1
kind: Service
metadata:
  name: anomaly-service
  namespace: anomaly
spec:
  selector:
    app: anomaly-service
  ports:
    - port: 8083
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anomaly-ingress
  namespace: anomaly
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: sigma
    alb.ingress.kubernetes.io/group.order: "2"
spec:
  rules:
    - http:
        paths:
          - path: /api/anomalies
            pathType: Prefix
            backend:
              service:
                name: anomaly-service
                port:
                  number: 8083
